language: php

before_install:
  - pip install --user codecov
  - pip install -U requires.io

install:
  - travis_retry composer install --no-interaction --prefer-dist --dev -o

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction --dev -o

script:
  - php vendor/bin/phpunit -c build/travis-ci.xml

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)
  - requires.io update-site -t 0f5c9e1926722664b9de90cb1114285ae2b6ed87 -r REPO

matrix:
  allow_failures:
    - php: hhvm

notifications:
  email: false
