language: php

install:
  - travis_retry composer install --no-interaction --prefer-dist --dev -o

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction --dev -o

script: php vendor/bin/phpunit -c build/travis-ci.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - php: hhvm

notifications:
  email: false
