language: php

install:
  - travis_retry composer install --no-interaction --prefer-source

php:
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit vendor/bin/phpunit -c build/travis-ci.xml

matrix:
  allow_failures:
    - php: hhvm

notifications:
  email: false
